### ISSUE TITLE
还维护嘛？

### ISSUE THREAD

**Issue by codewithyou** [sofn/app-engine#1]
怎么运行？？？？

**Comment by sofn** [comment]
维护，最近一段时间工作比较忙，过年期间会更新一些优化。

运行项目方式：
执行: gradle run
Java运行: Application.java
执行: ./gradlew run，此方式不用安装gradle

详见wiki

**Comment by codewithyou** [comment]
多谢，我去温习了下 spring boot ，建议 文档 可以做的全一点。在此感谢你的回答。
